name: Update visual regression tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Debug
      run: |
        echo ${GITHUB_REF##*/}
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
        npm install -g backstopjs --unsafe-perm=true --allow-root
        npm ci
        ./node_modules/.bin/lerna bootstrap
    - name: Generate new reference screenshots
      run: |
        nohup npm run larva > /dev/null 2>&1 &
        sleep 5
        npm run backstop -- reference
      env:
        CI: true
    - name: Commit results
      uses: EndBug/add-and-commit@v8
      with:
        add: 'backstop_data'
        message: 'chore: updated backstop reference screenshots'
        new_branch: "update-screenshots"

