name: Update visual regression tests

on: [push]

env:
  BRANCH_NAME: ${GITHUB_REF##*/}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        touch backstop_data/new.txt
    - name: Debug
      run: |
        echo ${{ steps.branch-name.outputs.current_branch }}
    - name: Commit results
      uses: EndBug/add-and-commit@v8
      with:
        add: 'backstop_data'
        message: 'chore: updated backstop reference screenshots'
        new_branch: update-$BRANCH_NAME
