name: Test themes

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - name: Prepare node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check out themes
        run: |
          mkdir ~/.ssh/
          echo ${BITBUCKET_READ_ONLY_SSH_KEY} > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan bitbucket.org

          git clone git@bitbucket.org:penskemediacorp/${BITBUCKET_REPO_SLUG}.git

          ls -la theme

          cd theme
          npm ci
          npm run prod
        env:
          BITBUCKET_READ_ONLY_SSH_KEY: ${{ secrets.BITBUCKET_READ_ONLY_SSH_KEY }}
          BITBUCKET_REPO_SLUG: pmc-artnews-2019
