name: Test themes

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 14.x ]
        bitbucket-repo-slug: [
          'pmc-artnews-2019',
          'pmc-indiewire-2016',
          'pmc-hollywoodreporter-2021',
        ]

    env:
      BITBUCKET_REPO_SLUG: ${{ matrix.bitbucket-repo-slug }}
      BITBUCKET_READ_ONLY_SSH_KEY: ${{ secrets.BITBUCKET_READ_ONLY_SSH_KEY }}
      THEME_DIR: theme

    steps:
      - name: Prepare node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check out themes
        run: |
          mkdir ~/.ssh/
          echo "${BITBUCKET_READ_ONLY_SSH_KEY}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan bitbucket.org > ~/.ssh/known_hosts

          git clone git@bitbucket.org:penskemediacorp/${BITBUCKET_REPO_SLUG}.git "${THEME_DIR}"
          ls -la "${THEME_DIR}"

          cd "${THEME_DIR}/assets"
          npm ci
          npm run prod

          # TODO: remove these after build issues are resolved.
          git status
          git diff --exit-code
