name: Test themes

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - name: Prepare node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check out themes
        run: |
          which git
          git --version
          pwd
          ls -la
          echo $BITBUCKET_REPO_SLUG

          git clone https://${BITBUCKET_READ_ONLY_USER_NAME}:${BITBUCKET_READ_ONLY_USER_PASS}@bitbucket.org/penskemediacorp/${BITBUCKET_REPO_SLUG}.git theme
          ls -la theme
        env:
          BITBUCKET_READ_ONLY_USER_NAME: ${{ secrets.BITBUCKET_READ_ONLY_USER_NAME }}
          BITBUCKET_READ_ONLY_USER_PASS: ${{ secrets.BITBUCKET_READ_ONLY_USER_PASS }}
          BITBUCKET_REPO_SLUG: pmc-artnews-2019
