name: Visual Regression Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm install -g backstopjs --unsafe-perm=true --allow-root
        npm ci
        ./node_modules/.bin/lerna bootstrap
    - name: Run Tests
      run: |
        nohup npm run larva > /dev/null 2>&1 &
        sleep 5
        npm run backstop -- test
      env:
        CI: true
    - name: Archive Backstop results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: backstop-results
        path: backstop_data
    - name: Repository dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT1 }}
        repository: ${{ github.repository }}
        event-type: my-event
        client-payload: '{"prnumber": "${{ github.event.number }}", "checkrunid": "${{ github.run_id }}"}'

    # - name: Add artifact links to pull request and related issues step
    #   uses: tonyhallett/artifacts-url-comments@v1.1.0
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #       prefix: Here are the artifacts
    #       suffix: Have a nice day.
    #       format: name
    #       addTo: pullandissues

  report:
    runs-on: [ubuntu-latest]
    needs: build
    steps:
    - name: echo value
      run: |
        echo ${{ github.event.client_payload.prnumber }}
        echo ${{ github.event.client_payload.checkrunid }}
    - name: get check_suite_id
      id: getsuiteid
      run: |
        URL="https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.client_payload.checkrunid }}"
        check_suite_id=$(curl -s -u admin:${{ secrets.GITHUB_TOKEN }} $URL | jq -r '.check_suite_url' | awk -F "/" '{print $NF}')
        echo $check_suite_id
        echo "::set-output name=suiteid::$check_suite_id"
    - name: get artifacts_id
      id: getartid
      run: |
        URL="https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.client_payload.checkrunid }}/artifacts"
        artifacts_id=$(curl -s -u admin:${{ secrets.GITHUB_TOKEN }} $URL | jq '.artifacts[].id')
        echo $artifacts_id
        echo "::set-output name=artid::$artifacts_id"
    - name: check url
      run: |
        echo https://github.com/${{ github.repository }}/suites/${{ steps.getsuiteid.outputs.suiteid }}/artifacts/${{ steps.getartid.outputs.artid }}
    - name: comment pr
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.client_payload.prnumber }}
        body: |
          The artifacts url is https://github.com/${{ github.repository }}/suites/${{ steps.getsuiteid.outputs.suiteid }}/artifacts/${{ steps.getartid.outputs.artid }}
