name: Visual Regression Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Comment Regression test results on PR
      uses: actions/github-script@0.9.0
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const output = `
            #### Backstop Results
            <details>
              <summary>View the results</summary>
              <p>
                <a href="#{{ github.workflow.job.id }}">
                  View the results
                </a>
              </p>
            ### When the results contain changes you want to retain
            <details>
              <summary>Update the reference screenshots</summary>
              <p>
                <a href="#">Run the Update visual regression tests</a> on this feature branch.
                This will create a new branch with reference screenshots.
                Then you will need to open a pull request to this branch to update it.
              </p>
          `;
            github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: output,
            });
