name: Visual Regression Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm install -g backstopjs --unsafe-perm=true --allow-root
        npm ci
        ./node_modules/.bin/lerna bootstrap
    - name: Run Tests
      run: |
        nohup npm run larva > /dev/null 2>&1 &
        sleep 5
        npm run backstop -- test
      env:
        CI: true
    - name: Archive Backstop results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: backstop-results
        path: backstop_data
    - name: Add artifact links to pull request and related issues step
      uses: tonyhallett/artifacts-url-comments@v1.1.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          prefix: Here are the artifacts
          suffix: Have a nice day.
          format: name
          addTo: pullandissues
