name: Visual Regression Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - id: find-pull-request
      uses: jwalton/gh-find-current-pr@v1
      with:
        # Can be "open", "closed", or "all".  Defaults to "open".
        state: open
    - name: Debug
      run: echo ${{ github.run_id }}
    - name: Comment Regression test results on PR
      uses: peter-evans/create-or-update-comment@v2
      if: github.event_name == 'push'
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        repository: ${{ github.repository }}
        issue-number: ${{ steps.find-pull-request.outputs.number }}
        comment-author: 'github-actions[bot]'
        body: |
            ### Backstop Visual Regression Tests Failed
            <p>
                <a href="https://github.com/penske-media-corp/pmc-larva/actions/runs/${{ github.run_id }}">
                View the results
                </a>. Look under the section titled "Artifacts". Download the artifact, then on your local machine, find backstop_results/index.html in the downloaded directory. Open it in a browser to view the screenshot comparison.
            </p>

            ### When the results contain changes you want to retain

            #### Update the reference screenshots
            <p>
                <a href="#">Run the Update visual regression tests</a> on this feature branch.
                This will create a new branch with reference screenshots.
                Then you will need to open a pull request to this branch to update it.
            </p>

