name: Visual Regression Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm install -g backstopjs --unsafe-perm=true --allow-root
        npm ci
        ./node_modules/.bin/lerna bootstrap
    - name: Run Tests
      run: |
        nohup npm run larva > /dev/null 2>&1 &
        sleep 5
        npm run backstop -- test
      env:
        CI: true
    - name: Archive Backstop results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: backstop-results
        path: backstop_data
    - name: Comment Regression test results on PR
      uses: actions/github-script@0.9.0
      if: github.event_name == "pull_request"
      with:
        script: |
          const output = `
            #### Backstop Results
            <details>
              <summary>View the results</summary>
              <p>
                <a href="#{{ github.workflow.job.id }}">
                  View the results
                </a>
              </p>
            ### When the results contain changes you want to retain
            <details>
              <summary>Update the reference screenshots</summary>
              <p>
                <a href="#">Run the Update visual regression tests</a> on this feature branch.
                This will create a new branch with reference screenshots.
                Then you will need to open a pull request to this branch to update it.
              </p>
          `;
            github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: output,
            });
