name: Test & Lint Larva

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - run: ./node_modules/.bin/lerna bootstrap
      - name: Run Tests
        run: npm test
      - name: Run Linters
        run: npm run lint
        env:
          CI: true
